### ISSUE TITLE
coordinates like 45/20/N, 3/00/E

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/mappings-tracker#13]
@jimkont: do you handle coordinates like this?
https://fr.wikipedia.org/wiki/Auvergne?action=edit&veswitched=1

```
 | latitude                  = 45/20/N
 | longitude                 = 3/00/E
```

**Comment by Nono314** [comment]
Yes, they are taken care of since dbpedia/extraction-framework/issues/76

I have added the appropriate mapping to [Infobox Région de France](http://mappings.dbpedia.org/index.php/Mapping_fr:Infobox_R%C3%A9gion_de_France) and the result can be seen on [Mapping test page](http://mappings.dbpedia.org/server/mappings/fr/extractionSamples/Mapping_fr:Infobox_R%C3%A9gion_de_France)

**Comment by jplu** [comment]
@Nono314 your mapping is a error, the properties latitude and longitude don't exist for this infobox according to the doc: http://fr.wikipedia.org/wiki/Mod%C3%A8le:Infobox_R%C3%A9gion_de_France

It is an error from the Wikipedia page. So this new mapping has to be removed has it doesn't respects the model.

**Comment by jcsahnwaldt** [comment]
@jplu The properties exist, they just aren't documented: http://fr.wikipedia.org/w/index.php?diff=prev&oldid=94809842

**Comment by VladimirAlexiev** [comment]
Close it then?

**Comment by jplu** [comment]
So ok!
